config/routes.rb
Rails.application.routes.draw do
  mount ResqueWeb::Engine => '/resque_web'
  get 'dashboard/index'
  resources :transactions
  resources :ratios
  resources :ammounts
  resources :currencies do
    member do
        post 'buy', to: 'currencies#buy'
        get 'open_modal', to: 'currencies#open_modal'
    end
    collection do
        get 'get_currency_data', to: 'currencies#get_currency_data'
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #root 'sessions#create'
  root to: 'dashboard#index'

  get '/welcome' => 'welcome#new'

  get '/signup' => 'users#new'
  post '/signup' => 'users#create'

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'
end

app/models/currency.rb
class Currency < ApplicationRecord
	has_many :ratios

	def price(from_currency = nil)
		from_ratio = from_currency.nil? ? Currency.default_ratio : from_currency.ratios.last.ratio
		(from_ratio / current_ratio).round(3)
	end

	def current_ratio
		self.ratios.last.ratio
	end

	def self.default_ratio
		Currency.find_by(name: 'USD').ratios.last.ratio
	end
end

app/controllers/currencies_controller.rb
class CurrenciesController < ApplicationController
  before_action :authorize
  before_action :set_currency, only: [:open_modal, :buy, :show, :edit, :update, :destroy]

  # GET /currencies
  # GET /currencies.json
  def index
    @currencies = Currency.where.not(default: true)
  end

  # GET /currencies/1
  # GET /currencies/1.json
  def show
  end

  def set_ammount

  end


  def get_currency_data

  final_array = []
  current_user.ammounts.each do |a|
    
      quantity = a.quantity * a.currency.price.round(3)
      currency_name = a.currency.name
      final_array << [currency_name,quantity]
    
    end
      render json: { stats: final_array }
  end


  def buy
    
    original_currency_amount    = params[:original_currency_ammount]
    final_currency_ammount = params[:final_currency_ammount]
    original_currency_id = params[:original_currency_id]
    final_currency_id = @currency.id
             
    original_ammount_remain = original_currency_amount.to_f-((final_currency_ammount.to_f * @currency.price(Currency.find(original_currency_id))).round(3))

    if(original_ammount_remain == 0)
        Ammount.where("user_id = ? AND currency_id = ?", current_user.id, original_currency_id).delete_all
      else
        Ammount.where("user_id = ? AND currency_id = ?", current_user.id, original_currency_id).update(quantity: original_ammount_remain)
      end


    if Ammount.where("user_id = ? AND currency_id = ?", current_user.id, final_currency_id).blank?
      Ammount.create(
        user_id: current_user.id,
        quantity: final_currency_ammount.to_f,
        currency_id: @currency.id
        )
    else
        existing_ammount = Ammount.where("user_id = ? AND currency_id = ?", current_user.id, @currency.id).pluck(:quantity).first.to_f
        Ammount.where("user_id = ? AND currency_id = ?", current_user.id, @currency.id).update(quantity: final_currency_ammount.to_f + existing_ammount)
    end
 
  Transaction.create(user_id: current_user.id, original_currency_id: original_currency_id, original_currency_ammount: original_currency_amount, final_currency_id: final_currency_id, final_currency_ammount: final_currency_ammount)

    redirect_to currencies_path, notice: 'Successfully bought some coins!'
  end

  # GET /currencies/new
  def new
    @currency = Currency.new
  end

  def open_modal
    @ammount = params[:quantity].to_f
    render :partial => 'render_modal'
  end

  # GET /currencies/1/edit
  def edit
  end

  # POST /currencies
  # POST /currencies.json
  def create
    @currency = Currency.new(currency_params)

    respond_to do |format|
      if @currency.save
        format.html { redirect_to @currency, notice: 'Currency was successfully created.' }
        format.json { render :show, status: :created, location: @currency }
      else
        format.html { render :new }
        format.json { render json: @currency.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /currencies/1
  # PATCH/PUT /currencies/1.json
  def update
    respond_to do |format|
      if @currency.update(currency_params)
        format.html { redirect_to @currency, notice: 'Currency was successfully updated.' }
        format.json { render :show, status: :ok, location: @currency }
      else
        format.html { render :edit }
        format.json { render json: @currency.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /currencies/1
  # DELETE /currencies/1.json
  def destroy
    @currency.destroy
    respond_to do |format|
      format.html { redirect_to currencies_url, notice: 'Currency was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_currency
      @currency = Currency.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def currency_params
      params.require(:currency).permit(:name, :symbol, :default)
    end
    def verify_user
  redirect_to '/login' unless current_user 
end
end

app/helpers/currencies_helper.rb
module CurrenciesHelper
end

app/views/currencies/_currency_modal.html.erb
<div class="modal-content">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
</div>
    <div class="modal-body">
		<table class = "table">
			<thead>
				<th>Price</th>
				<th>Coin to buy</th>
				<th>Action</th>
			</thead>
			<tbody>
	    	<% current_user.ammounts.each do |ammount| %>
	    		<tr>
	    			<td><%= ammount.currency.name %> <%= (@ammount * @currency.price(ammount.currency)).round(3)  %></td>
	    			<td><%= @currency.name %> <%= @ammount %></td>

	    			<% if(ammount.quantity.to_f >= (@ammount * @currency.price(ammount.currency)).round(3)) %>
	    			<%                                  #currency_to_buy  #quantity_to_buy       #ID of buying currency           %>
	    			<td><%= link_to 'Buy', buy_currency_path(@currency, final_currency_ammount: @ammount, original_currency_id: ammount.currency.id, original_currency_ammount: ammount.quantity), method: :post %></td>
	    			<% else %>
	    			<td>You don't have enough</td>
	    			<% end %>
	    		</tr>
	    	<% end %>
	    	</tbody>
    	</table>
    </div>
    <div class="modal-footer">
      <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
    </div>
 </div>

app/views/currencies/_form.html.erb
<%= form_with(model: currency, local: true) do |form| %>
  <% if currency.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(currency.errors.count, "error") %> prohibited this currency from being saved:</h2>

      <ul>
      <% currency.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :currency_name %>
  </div>

  <div class="field">
    <%= form.label :symbol %>
    <%= form.text_field :symbol, id: :currency_symbol %>
  </div>

  <div class="field">
    <%= form.label :default %>
    <%= form.check_box :default, id: :currency_default %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/currencies/_render_modal.js.erb
$("#currency-<%= @currency.id.to_s %>").html("<%= escape_javascript(render 'currency_modal') %>");
$("#currency-<%= @currency.id.to_s %>").modal('show');

app/views/currencies/edit.html.erb
<h1>Editing Currency</h1>

<%= render 'form', currency: @currency %>

<%= link_to 'Show', @currency %> |
<%= link_to 'Back', currencies_path %>

app/views/currencies/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Currencies</h1>

<div id="chart"></div>

<table class='table'>
  <thead>
    <tr>
      <th>Name</th>
      <th>Price</th>
      <th>Amount to buy</th>
      <th>Actions</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @currencies.each do |currency| %>
      <tr>
        <td>
          <%= image_tag("#{(currency.name.downcase.gsub(' ','_'))}.svg",size: '23x23') %> 
          <%= currency.name %> (<%= currency.symbol %>)
        </td>
        <td><%= number_to_currency(currency.price) %></td>
        
        <%= form_with url: open_modal_currency_path(currency.id), id: "buy-form-#{currency.id}", method: :get do |f| %>
          <td><%= f.number_field :quantity, step: :any %></td>
          <td><%= f.submit 'Buy', class: 'btn btn-primary', id: "buy-#{currency.id}"%></td>
         

         <div class="modal fade" style="padding: 60px;" id="currency-<%= currency.id.to_s %>" tabindex="-1" role="dialog">
          <div class="modal-dialog" role="document">
          </div>
          </div>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Currency', new_currency_path %>

app/views/currencies/new.html.erb
<h1>New Currency</h1>

<%= render 'form', currency: @currency %>

<%= link_to 'Back', currencies_path %>

app/views/currencies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @currency.name %>
</p>

<p>
  <strong>Symbol:</strong>
  <%= @currency.symbol %>
</p>

<p>
  <strong>Default:</strong>
  <%= @currency.default %>
</p>

<%= link_to 'Edit', edit_currency_path(@currency) %> |
<%= link_to 'Back', currencies_path %>