config/routes.rb
Rails.application.routes.draw do
  mount ResqueWeb::Engine => '/resque_web'
  get 'dashboard/index'
  resources :transactions
  resources :ratios
  resources :ammounts
  resources :currencies do
    member do
        post 'buy', to: 'currencies#buy'
        get 'open_modal', to: 'currencies#open_modal'
    end
    collection do
        get 'get_currency_data', to: 'currencies#get_currency_data'
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #root 'sessions#create'
  root to: 'dashboard#index'

  get '/welcome' => 'welcome#new'

  get '/signup' => 'users#new'
  post '/signup' => 'users#create'

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'
end

app/models/ammount.rb
class Ammount < ApplicationRecord
	belongs_to :user
	belongs_to :currency
end

app/controllers/ammounts_controller.rb
class AmmountsController < ApplicationController
  before_action :authorize
  before_action :set_ammount, only: [:show, :edit, :update, :destroy]

  # GET /ammounts
  # GET /ammounts.json
  def index
    @ammounts = Ammount.all
  end

  # GET /ammounts/1
  # GET /ammounts/1.json
  def show
  end

  # GET /ammounts/new
  def new
    @ammount = Ammount.new
  end

  # GET /ammounts/1/edit
  def edit
  end

  # POST /ammounts
  # POST /ammounts.json
  def create
    @ammount = Ammount.new(ammount_params)

    respond_to do |format|
      if @ammount.save
        format.html { redirect_to @ammount, notice: 'Ammount was successfully created.' }
        format.json { render :show, status: :created, location: @ammount }
      else
        format.html { render :new }
        format.json { render json: @ammount.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ammounts/1
  # PATCH/PUT /ammounts/1.json
  def update
    respond_to do |format|
      if @ammount.update(ammount_params)
        format.html { redirect_to @ammount, notice: 'Ammount was successfully updated.' }
        format.json { render :show, status: :ok, location: @ammount }
      else
        format.html { render :edit }
        format.json { render json: @ammount.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ammounts/1
  # DELETE /ammounts/1.json
  def destroy
    @ammount.destroy
    respond_to do |format|
      format.html { redirect_to ammounts_url, notice: 'Ammount was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ammount
      @ammount = Ammount.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ammount_params
      params.require(:ammount).permit(:user_id, :quantity, :currency_id)
    end
end

app/helpers/ammounts_helper.rb
module AmmountsHelper
end

app/views/ammounts/_form.html.erb
<%= form_with(model: ammount, local: true) do |form| %>
  <% if ammount.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(ammount.errors.count, "error") %> prohibited this ammount from being saved:</h2>

      <ul>
      <% ammount.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.number_field :user_id, id: :ammount_user_id %>
  </div>

  <div class="field">
    <%= form.label :quantity %>
    <%= form.text_field :quantity, id: :ammount_quantity %>
  </div>

  <div class="field">
    <%= form.label :currency_id %>
    <%= form.number_field :currency_id, id: :ammount_currency_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/ammounts/edit.html.erb
<h1>Editing Ammount</h1>

<%= render 'form', ammount: @ammount %>

<%= link_to 'Show', @ammount %> |
<%= link_to 'Back', ammounts_path %>

app/views/ammounts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Ammounts</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Quantity</th>
      <th>Currency</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ammounts.each do |ammount| %>
      <tr>
        <td><%= ammount.user_id %></td>
        <td><%= ammount.quantity %></td>
        <td><%= ammount.currency_id %></td>
        <td><%= link_to 'Show', ammount %></td>
        <td><%= link_to 'Edit', edit_ammount_path(ammount) %></td>
        <td><%= link_to 'Destroy', ammount, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Ammount', new_ammount_path %>

app/views/ammounts/new.html.erb
<h1>New Ammount</h1>

<%= render 'form', ammount: @ammount %>

<%= link_to 'Back', ammounts_path %>

app/views/ammounts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @ammount.user_id %>
</p>

<p>
  <strong>Quantity:</strong>
  <%= @ammount.quantity %>
</p>

<p>
  <strong>Currency:</strong>
  <%= @ammount.currency_id %>
</p>

<%= link_to 'Edit', edit_ammount_path(@ammount) %> |
<%= link_to 'Back', ammounts_path %>